//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanXeOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Icon { get; set; }
        public string TextMenu { get; set; }
        public string Link { get; set; }
        public int RoleId { get; set; }
    
        public virtual Quyen Quyen { get; set; }
    }
}
